about/urls.py
from django.urls import path, include
from .views import index,form,savekegi


app_name = "about"
urlpatterns = [
    path('about/', index, name='index'),
    path('form/', form, name='form'),
    path('form/savekegi',savekegi),
]

article/urls.py
from django.urls import path

from . import views

app_name = "article"

urlpatterns = [
    path('', views.index, name='article'),
    path('detail/<str:pk>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('get_all/', views.get_articles, name='get'),
    path('search/result/', views.search, name="search_has_query"),
    path('search/', views.get_search, name="search")
]

tk2_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('authentication/', include('authentication.urls')),
    path('', include('about.urls')),
    path('article/', include('article.urls'))
]

article/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from authentication.models import Account

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey(Account, on_delete=models.CASCADE)
    topik = models.CharField(max_length=100)
    judul = models.CharField(max_length=100)
    image = models.CharField(max_length=400)
    date = models.DateField(auto_now_add=True)
    content = models.TextField()

class ArticleReview(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

article/forms.py
from django import forms
from .models import Article

class formulir(forms.ModelForm):
    class Meta:
        model = Article   
        fields="__all__"  

article/views.py
from django.shortcuts import render, redirect
from .models import Article, ArticleReview
from . import forms
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from authentication.models import Account
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
import math

def index(request):
    VarA = forms.formulir()
    VarA_dictio = {
        'formulir' : VarA,
    }
    return render(request, 'article/index.html', VarA_dictio)


def detail(request, pk):
    article = Article.objects.get(id=pk)
    context = {'article' : article}
    return render(request, 'article/detail.html', context)

@csrf_exempt
def add(request):
    if request.method == "POST":
        form = forms.formulir({
            'author' : request.user,
            'topik' : request.POST['topik'],
            'judul' : request.POST['judul'],
            'image' : request.POST['image'],
            'content' : request.POST['content'],
        })
        if(form.is_valid()):
            print("valid")
            new_article = form.save()
            return JsonResponse({'status' : 'success', 'id': new_article.id})
        else:
            return JsonResponse({'status' : 'failed'})


def get_articles(request):
    articles = Article.objects.all()
    article_list = serializers.serialize('json', articles)
    return HttpResponse(article_list, content_type="text/json-comment-filtered")


def search(request):
    DEFAULT_PAGINATION = 20
    DEFAULT_PAGES_INTERVAL = 5
    DEFAULT_NEXT_INTERVAL = 3
    if request.method == "POST":
        search_query = request.POST["search_query"]
        current_page = int(request.POST["current_page"])
        artikel_qs = Article.objects.filter(author__username__contains=search_query) | Article.objects.filter(topik__contains=search_query) | Article.objects.filter(judul__contains=search_query)
        max_qs = artikel_qs.count()
        pages_max = math.ceil(max_qs / DEFAULT_PAGINATION)
        if pages_max < 5:
            accessible_pages = list(range(1,pages_max+1))
        elif(current_page <=3):
            accessible_pages = list(range(1,6))
        elif (current_page > pages_max - DEFAULT_PAGES_INTERVAL):
            accessible_pages = list(range(pages_max-DEFAULT_PAGES_INTERVAL+1, pages_max+1))
        else:
            accessible_pages = list(range(current_page, current_page +  DEFAULT_PAGES_INTERVAL))
        artikel_qs = artikel_qs[((current_page-1)*DEFAULT_PAGINATION):(current_page*DEFAULT_PAGINATION)]
        if artikel_qs.count() > DEFAULT_PAGINATION:
            max_qs = DEFAULT_PAGINATION
        return render(request, "article/result.html", {"artikels":artikel_qs, "max_qs":max_qs, "pages_max":pages_max, "current_page":current_page, "accessible_pages":accessible_pages, "search_query":search_query})
    return redirect('/article/search/')

def get_search(request):
    return render(request, "article/search.html")

article/templates/article/detail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
        .content {
            margin-right: 150px !important;
            margin-left: 150px !important;
        }
    </style>
    <title>CegahCovid</title>
</head>

<body>
    <!-- navbar -->
    {% include 'navbar.html' with current="articles" %}

    <div class="content pt-5">
        <div class="pt-5 row">
            <h1 class="px-2"><span style="color: #9C2208; font-size: larger"><b>{{ article.topik }}</b></span>
                <br><i>{{ article.judul }}</i><br><span style="font-size: large">{{ article.author }} | {{ article.date }}</span></h1>
        </div>
        <div class="row">
            <div class="d-flex justify-content-center w-100">
                <img class="img-responsive" src="{{ article.image }}" width="100%" height="auto">
            </div>
            <div class="w-100 break"></div>
            <div class="col-sm">
                <p style="text-align: justify">{{ article.content }}
                </p>
            </div>
        </div>
    </div>

    <script src="{% static 'article/script2.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</body>

</html>

article/templates/article/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="url_add" content="{% url 'article:add' %}">
    <meta name="url_article" content="{% url 'article:article' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'article/style.css' %}">
    <style>
        nav {
            position: fixed !important;
            top: 0;
            width: 100%;
        }
    </style>
    <title>CegahCovid</title>
</head>

<body>
    <!-- navbar -->
    {% include 'navbar.html' with current="articles" %}

    <div style="margin-top: 5rem;" class="p-md-5 p-1">
        {% if user.is_authenticated %}
        <h1>Tulis artikelmu di sini!</h1>
        <div id="judul">Judul Artikel : </div>
        <div class="">
            <div class="article-container d-flex flex-wrap">
                <!-- Ajax -->
            </div>
            <div class="container mt-5 border-top pt-3" id="Post">

                <form method="post">
                    <div class="form-group">
                        <label for="topik">Topik</label> {{ formulir.topik }}
                    </div>
                    <div class="form-group">
                        <label for="judul">Judul</label> {{ formulir.judul }}
                    </div>
                    <div class="form-group">
                        <label for="image">Tautan Gambar</label> {{ formulir.image }}
                    </div>
                    <div class="form-group">
                        <label for="content">Isi</label> {{ formulir.content }}
                    </div>
                    <button type="submit" id="submit" class="btn btn-primary mb-4 btn-add-article">Submit</button>
                </form>
            </div>
        </div>
        {% else %}
        <h1>Harap login sebelum menulis artikel!</h1>
        {% endif %}
    </div>
    </div>
    {% block js %}
    <script>
        $("input").addClass("form-control")
        $("textarea").addClass("form-control")
        $("input").eq(0).attr("placeholder", 'Topik')
        $("input").eq(1).attr("placeholder", 'Judul')
        $("input").eq(2).attr("placeholder", 'Tautan Gambar')
        $("input").eq(3).attr("placeholder", 'Isi')
        $("form").submit(function(e) { // onSubmit event
            e.preventDefault();
        });
    </script>
    <script src="{% static 'article/script.js' %}"></script>
    {% endblock js %}

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>



</body>

</html>

article/templates/article/result.html
{% extends 'template.html' %}
{% load static %}

{% block title %}
    Search
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'authentication/templatestyle.css' %}">
    <style>
        .content-placeholder{
            justify-content:unset;
            overflow-x:hidden;
        }
        .content-container{
            position:relative;
            z-index:20;
            margin:0 3.125rem;
        }
        .content-container .search-box, .content-container, .content-container .search-box form, .content-container .search-box form input[type="text"] {
            width:100%;
        }
        .content-container .search-box form button{
            display:inline-block;
            height:calc(100% - 2rem);
            background:transparent;
            border:none
        }
        .content-container .search-box .button-magnifying{
            position:absolute;
            top:0;
            right:0;
            display:inline-flex;
            justify-content:flex-end;
            align-items:center;
            margin-right:0.5rem;
            margin-top:-2px;
            height:100%;
        }
        .content-container .search-box form button img{
            width:auto;
            height:100%;
        }
        .content-container .search-box form {
            margin-top:3.125rem;
            position:relative;
        }
        .content-container .search-box form input[type="text"]{            
            padding:0.5rem 1rem;
            font-size:1.5rem;
            background:#C4C4C4;
            color:#413C3D;
            border:2px solid #000;
            border-radius:10px;
        }
        .content-container .search-box form input[type="text"]:focus{
            outline:none;
        }
        .content-container p.results-text{
            font-size:1rem;
            margin-top:1.5rem;
            font-weight:bold;
        }
        .content-container .showing-results{
            margin-top:0.5rem;
        }
        .showing-results .card .photo-placeholder img{
            width:250px;
            height:250px;
        }
        .showing-results .card{
            display:flex;
            flex-direction:row;
        }
        .showing-results .card .photo-placeholder{
            display:inline-block;
            margin-right:2.5rem;
        }
        .showing-results .card .text-placeholder{
            position:relative;
            min-height:250px;
            width:100%;
        }
        .showing-results .card{
            padding: calc(1.5rem + 1px) 1.875em;
            background:#413C3D;
            color:#E4E4E4;
            margin-bottom:calc(1.5rem + 1px);
        }
        .showing-results .card .text-placeholder h2.judul{
            font-size:1.5rem;
            font-weight:800;
            margin-bottom:10px;
        }
        .showing-results .card .text-placeholder h3.topik{
            font-size:1.25rem;
            font-weight:600;
            margin-bottom:10px;
        }
        .showing-results .card .text-placeholder p.text-paragraf{
            font-size:1rem;
            font-weight:400;
            text-align:justify;
        }
        .showing-results .card .text-placeholder a{
            position:absolute;
            bottom:0;
            left:0;
            color:#E4E4E4;
        }
        .circle-pagination{
            background:#413C3D;
            border-radius:50%;
            width:30px;
            height:30px;
            color:#C4C4C4;
            display:flex;
            justify-content:center;
            align-items:center;
            border:none;
        }
        .circle-pagination.active{
            background:#C4C4C4;
            color:#413C3D;
        }
        .pagination-bar{
            display:flex;
            justify-content:center;
            margin-top:5rem;
            margin-bottom:6rem;
        }
        .pagination-bar form{
            margin:0 0.5rem;
        }
        .pagination-bar form:first-child{
            margin-left:0;
        }
        .pagination-bar form:last-child{
            margin-right:0;
        }
        .content-placeholder{
            height:100% !important;
        }
        @media (max-width:768px){
            .showing-results .card {
                flex-direction:column;
                display:inline-flex;
                width:100%;
            }
            .showing-results .card .photo-placeholder img{
                width:100%;
                height:auto;
            }
            .showing-results .card .photo-placeholder{
                width:100%;
            }
            .showing-results .card .photo-placeholder{
                margin-bottom:1rem;
                margin-right:0;
            }
            .showing-results .card .text-placeholder .text-paragraf{
                margin-bottom:5rem;
            }
            .showing-results{
                display:flex;
                flex-direction:row;
                flex-wrap:wrap;
            }
        }
    </style>
{% endblock %}


{% block body %}
    {% include 'navbar.html' with current="search" %}
    <div class="content-placeholder">
        <div class="background">
            {% include 'authentication/backgrounds.html' %}
        </div>
        <div class="content-container">
            <div class="search-box">
                <form action="/article/search/result/" method="post">
                    {% csrf_token %}
                    <input type="text" name="search_query" placeholder="search here..." autocomplete="off">
                    <input type="hidden" name="current_page" value="1">
                    <div class="button-magnifying">
                        <button type="submit" value="submit">
                            <img src="{% static 'article/magnifying-glass.png' %}" alt="">
                        </button>
                    </div>
                </form>
            </div>
            <p class="results-text">
                Showing {{ artikels.count }}/{{ max_qs }} Results
            </p>
            <div class="showing-results">

                {% if max_qs > 0 %}
                    {% for artikel in artikels %}
                        <div class="card" >
                            <div class="photo-placeholder">
                                <img src="{{ artikel.image }}" alt="{{ artikel.judul }}">
                            </div>
                            <div class="text-placeholder">
                                <h2 class="judul">{{ artikel.judul }}</h2>
                                <h3 class="topik">{{ artikel.topik }}</h3>
                                <p class="text-paragraf">{{ artikel.content }}...</p>
                                <a href="/article/detail/{{ artikel.id }}/">Click to read more</a>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h1 class="not-found">
                        Pencarian tidak ditemukan.
                    </h1>
                {% endif %}
            </div>
            <div class="pagination-bar">
                {% for page in accessible_pages %}
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="current_page" value="{{ page }}">
                    <input type="hidden" name="search_query" value="{{ search_query }}">
                    {% if page == current_page %}
                        <button type="submit" class="circle-pagination active">
                            {{ page }}
                        </button>
                    {% else %}
                        <button type="submit" class="circle-pagination">
                            {{ page }}
                        </button>
                    {% endif %}
                </form> 
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

article/templates/article/search.html
{% extends 'template.html' %}
{% load static %}

{% block title %}
    Search
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'authentication/templatestyle.css' %}">
    <style>
        .content-container .content-card h1.search-title{
            font-size:2rem;
        }
        .content-container .content-card h3.instruction{
            font-size:1.2rem;
        }
        .content-container .content-card .search-container form input[type="text"]{
            padding:0.5rem 1rem;
            font-size:1.5rem;
            border: 2px solid #000;
            border-radius:10px;
            box-sizing:border-box;
            color:#413C3D;
            background:#C4C4C4;
            margin-top:1rem;
            width:100%;
            max-width:500px;
        }
        .content-container .content-card .search-container form input[type="text"]:focus{
            outline:none;
        }
        .content-container .content-card .search-container form input[type="submit"]{
            padding:0.5rem 1.5rem;
            border-radius:20px;
            background:#C4C4C4;
            color:#413C3D;
            font-weight:bold;
            border:none;
            margin-top:0.5rem;
        }
    </style>
{% endblock %}


{% block body %}
    {% include 'navbar.html' with current="search" %}
    <div class="content-placeholder">
        <div class="background">
            {% include 'authentication/backgrounds.html' %}
        </div>
        <div class="content-container">
            <div class="content-card">
                <h1 class="search-title">CegahCovid</h1>
                <h3 class="instruction">Search your Article</h3>
                <div class="search-container">
                    <form action="/article/search/result/" method="post">
                        {% csrf_token %}
                        <input type="text" name="search_query" placeholder="search here...">
                        <input type="hidden" name="current_page" value="1">
                        <input type="submit" value="Search">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}