about/urls.py
from django.urls import path, include
from .views import index,form,savekegi


app_name = "about"
urlpatterns = [
    path('about/', index, name='index'),
    path('form/', form, name='form'),
    path('form/savekegi',savekegi),
]

tk2_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('authentication/', include('authentication.urls')),
    path('', include('about.urls')),
    path('article/', include('article.urls'))
]

about/models.py
from django.db import models

# Create your models here.

CHOICES= [
    ('Full Stack Developer', 'Full Stack Developer'),
    ('Front-End Developer', 'Front-End Developer'),
    ('Back-End Developer', 'Back-End Developer'),
    ]
class User(models.Model):
    name= models.CharField(max_length=100)
    role= models.CharField(max_length=100, choices= CHOICES)

about/forms.py
from django import forms  
from .models import User


CHOICES= [
    ('Full Stack Developer', 'Full Stack Developer'),
    ('Front-End Developer', 'Front-End Developer'),
    ('Back-End Developer', 'Back-End Developer'),
    ]

class UserForm(forms.ModelForm):
    name= forms.CharField(max_length=100)
    role= forms.CharField(widget=forms.Select(choices=CHOICES))
    class Meta:
        model = User
        fields =['name','role']

about/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.views.generic import FormView  
from .models import User 
from .forms import UserForm


def index(request):
    objs = User.objects.all()
    return render(request, 'about/indexx.html',{'objs':objs})
def form(request):
    response={ 'form':UserForm}
    return render(request, 'about/form.html',response)


def savekegi(request):
    form = UserForm(request.POST or None)
    f = form.save()
    if(form.is_valid and request.method == 'POST'):
        f.save()
        return HttpResponseRedirect('/about')
    else:
        return HttpResponseRedirect('/form')

about/templates/about/form.html
{% extends 'template.html' %}
{% load static %}

{% block title %}
    Form Member
{% endblock %}


{% block body %}
  {% include 'navbar.html' with current="form" %}
    
            
                <form action="savekegi" method="POST">
                    {% csrf_token %}
                    
                    <table  cellspacing="15" style="margin-left: auto; margin-right: auto; margin-top: 40px;" >
                        {{form.as_table}}
                    </table>
                    <input type="submit" class="btn btn-success" value="Submit" style="margin-bottom: 353px; margin-left: 660px; margin-top: 50px;"> 
            
                    
                    
                </form>
                
        
{% endblock %}

about/templates/about/indexx.html
{% extends 'template.html' %}
{% load static %}

{% block title %}
    About Us
{% endblock %}
{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
</script>

<script>
  $(document).ready(function(){
  $("img#content1").hover(function() {
      $("img#content1").addClass('transition');
  
  }, function() {
      $("img#content1").removeClass('transition');
  });
});
</script>
<script>
  $(document).ready(function(){
  $("img#content2").hover(function() {
      $("img#content2").addClass('transition');
  
  }, function() {
      $("img#content2").removeClass('transition');
  });
});
</script>
<script>
  $(document).ready(function(){
  $("img#content3").hover(function() {
      $("img#content3").addClass('transition');
  
  }, function() {
      $("img#content3").removeClass('transition');
  });
});
</script>
<script>
  $(document).ready(function(){
  $("img#content4").hover(function() {
      $("img#content4").addClass('transition');
  
  }, function() {
      $("img#content4").removeClass('transition');
  });
});
</script>
<script>
  $(document).ready(function () {
    var fold = $("#fold");
    fold.cliked = 1;
    fold.click(function () {
        $("#fold_p").text((fold.cliked++ % 2 == 0) ? "Ibnu Hambali" : "@itenkoui");
    });
});
</script>
<script>
  $(document).ready(function () {
    var fold = $("#igirza");
    fold.cliked = 1;
    fold.click(function () {
        $("#ig1").text((fold.cliked++ % 2 == 0) ? "Muhammad Irza" : "@muhammad_irza");
    });
});
</script>
<script>
  $(document).ready(function () {
    var fold = $("#igmario");
    fold.cliked = 1;
    fold.click(function () {
        $("#ig2").text((fold.cliked++ % 2 == 0) ? "Mario Serano" : "@rockattmario");
    });
});
</script>
<script>
  $(document).ready(function () {
    var fold = $("#igmax");
    fold.cliked = 1;
    fold.click(function () {
        $("#ig3").text((fold.cliked++ % 2 == 0) ? "Maximilian Aryo" : "@anak_quanta");
    });
});
</script>
<link rel="stylesheet" href="{% static 'about/style.css' %}">
{% endblock %}
{% block body %}
  {% include 'navbar.html' with current="about" %}
  
        <img src="{% static 'about/DR.png' %}" class="img-fluid" alt="Responsive image">
      <h1 style="font-size:4vw;text-align: center;position: relative;top: 70px;">About Us</h1>
      
      <p class="text-justify" style="margin-top: 100px;">CegahCovid adalah situs yang berisikan tentang artikel-artikel kesehatan,
        utamanya dalam rangka mencegah penyebarluasan pandemi COVID-19.
        Website ini menawarkan pengalaman baru dalam melakukan pencegahan,
        yaitu menulis artikel. User dapat menulis artikel yang nantinya akan dipublish.
        Dengan demikian, harapannya masyarakat akan lebih aware dalam menghadapi pandemi ini.</p>
      <h2 style="text-align: center;margin-top: 80px;">Team</h2>
        
      <div class="row" style="margin-top: 100px; margin-left: 100px; margin-right: 100px;">
        <div class="col-sm-3">
          <div class="card text-center">
            <img src="{% static 'about/ibnu.png' %}" id="content1" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
            <div class="card-body">
              <div id="fold">
                <h5 class="card-title" id="fold_p">Ibnu Hambali</h5>
              </div>
              <p class="card-text">Full Stack Developer</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card text-center">
            <img src="{% static 'about/irza.png' %}" id="content2" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
            <div class="card-body">
              <div id="igirza">
                <h5 class="card-title" id="ig1">Muhammad Irza</h5>
              </div>
              <p class="card-text">Full Stack Developer</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card text-center">
            <img src="{% static 'about/mario.png' %}" id="content3" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
            <div class="card-body">
              <div id="igmario">
                <h5 class="card-title" id="ig2">Mario Serano</h5>
              </div>
              <p class="card-text">Full Stack Developer</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card text-center">
            <img src="{% static 'about/aryo.png' %}" id="content4" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
            <div class="card-body">
              <div id="igmax">
                <h5 id="ig3" class="card-title">Maximilian Aryo</h5>
              </div>
              <p class="card-text">Full Stack Developer</p>
            </div>
          </div>
        </div>
      </div> 
    {% if user.is_authenticated %}
    <h2 style="text-align: center; margin-top: 100px;">Click button below to join us!</h2>
    
    <a class="btn btn-info" href="{% url 'about:form' %}" role="button"  style="margin-left: 50%;margin-right: auto; margin-top: 30px; margin-bottom: 30px;">join</a>
    {% if objs.count > 0 %}
    <h2 style="text-align: center;margin-top: 80px;">Additional Team Member</h2>
    
    <div class="row" style="margin-top: 100px; margin-left: 100px; margin-right: 100px;">
      {% for item in objs %}
      <div class="col-sm-3">
        <div class="card text-center" style="margin-bottom: 30px;">
          <img src="{% static 'about/fb1.png' %}" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
          <div class="card-body">
            <h5 class="card-title">{{item.name}}</h5>
            <p class="card-text">{{item.role}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    
    {% endif %}
  {% else %}
    <h2 style="text-align: center; margin-top: 100px; margin-bottom: 30px;">Login to view more!</h2>
    {% endif %}
 
    {% endblock %}